<div class="h-full w-full terms-conditions"> @include('partials.merch-header')
    <div class="container mx-auto justify-center pb-4">
        <h1 class="mt-12 text-3xl">Terms of Service</h1>
        <P class="mb-7 leading-5">Last Updated on December 28, 2021</P>
        <P class="mb-4 leading-5">These Terms of Service are effective immediately for all users registering an Account and any users accessing or using the Service without an Account.</P>
        <P class="mb-4 leading-5">These Terms govern your access to and use of our products and services, including those offered through our websites, events, communications (e.g., emails, phone calls, and texts) and mobile applications (collectively, the “<strong>Service</strong>”). By accessing or using the Service, you are agreeing to these Terms, which form a legally binding contract with Different Like You, Inc. (“DLY”), a Washington, DC corporation with its headquarters in Washington, DC. Do not access or use the Service if you are unwilling or unable to be bound by the Terms.</P>
        <P class="mb-4 leading-5"><strong>NOTE - THESE TERMS INCLUDE DISPUTE RESOLUTION PROVISIONS THAT, WITH LIMITED EXCEPTIONS, REQUIRE THAT (1) CLAIMS YOU BRING AGAINST DLY BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION, AND (2) YOU WAIVE YOUR RIGHT TO BRING OR PARTICIPATE IN ANY CLASS, GROUP, OR REPRESENTATIVE ACTION OR PROCEEDING.  </strong></p>
        <P class="mb-4 leading-5"><strong><u>Changes or Modifications</u></strong></p>
        <P class="mb-4 leading-5">DLY reserves the right, at its sole discretion, to change or modify portions of these Terms of Service at any time. Changes and modifications will be posted on this page and indicated at the top of this page by the date these terms were last revised. Any such changes will become effective immediately, and your continued use of the Service after the date any such changes become effective constitutes your acceptance of the new Terms of Service. You are advised to revisit these Terms on a regular basis as revised versions will be binding on you.</p>
        <P class="mb-4 leading-5"><strong><u>Access and Use of Service</u></strong></p>
        <ol class="list-decimal">
            <li class="mb-4 ml-4 leading-5"> <strong>Eligibility -</strong> To access or use the Service, you must have the requisite power and authority to enter into these Terms. You may not access or use the Service if you were previously banned from the Service or found in violation of these Terms. </li>
            <li class="mb-4 ml-4 leading-5"> <strong>Registration –</strong> All users of Service are required to register and generate a profile to access and use the Service. Upon registration for the Service, you agree to provide and maintain true, accurate, current and complete information about yourself as prompted by the Service’s registration form. Registration data and certain other information about you are governed by our Privacy Policy. </li>
            <li class="mb-4 ml-4 leading-5"><strong>Service Availability – D</strong>LY reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that DLY will not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</li>
            <li class="mb-4 ml-4 leading-5"><strong>Accounts - </strong>You are responsible for maintaining the confidentiality of your Account password. You are also responsible for all activities that occur in connection with your Account. You agree to notify us immediately of any suspicious activity on your Account, including, but not limited to, any unauthorized use of your Account. We reserve the right to close your Account at any time for any reason. Your Consumer Account is for your personal, non-commercial use only, and you may not create or use a Consumer Account for anyone other than yourself. You may not impersonate someone else, provide an email address other than your own, create multiple Accounts, or transfer your Consumer Account to another person without DLY’s prior approval. DLY will not be liable for any loss or damage arising from your failure to comply with this Section. </li>
            <li class="mb-4 ml-4 leading-5"><strong>Mobile Services and Communications - </strong>By accessing or using the Service, you consent to receive communications DLY through the Service, or through any other means such as emails, push notifications, text messages (including SMS and MMS), and phone calls. These communications may promote DLY or businesses listed on DLY, and may be initiated by DLY or businesses listed on DLY. </li>
        </ol>
        <P class="mb-4 leading-5">The Service includes certain services that are available via a mobile device, including (i) the ability to upload content to the Service via a mobile device, (ii) the ability to browse the Service and the Site from a mobile device and (iii) the ability to access certain features through an application downloaded and installed on a mobile device (collectively, the “Mobile Services”). To the extent you access the Service through a mobile device, your wireless service carrier’s standard charges, data rates and other fees may apply. In addition, downloading, installing, or using certain Mobile Services may be prohibited or restricted by your carrier, and not all Mobile Services may work with all carriers or devices. By using the Mobile Services, you agree that we may communicate with you by SMS, MMS, text message or other electronic means to your mobile device and that certain information about your usage of the Mobile Services may be communicated to us.</p>
        <P class="mb-4 leading-5"><strong>Conditions of Use</strong></p>
        <ol class="list-decimal">
            <li class="mb-4 ml-4 leading-5">
                <P class="mb-4 leading-5"><strong>Content –</strong> You are solely responsible for all audio, code, video, images, information, data, text, software, music, sound, photographs, graphics, messages or other materials (collectively, “Content”) that you upload, post, publish, display or in any way cause to be visible to other users and guests of the Service. You assume all risks associated with your Content, including anyone’s reliance on its quality, accuracy, or reliability, and any risks associated with personal information you disclose. You represent that you own or have the necessary permissions to use and authorize the use of your Content. You may not imply that your Content is in any way sponsored or endorsed by DLY. </p>
                <P class="mb-4 leading-5">DLY reserves the right to investigate and take appropriate legal action against anyone who, in DLY’s sole discretion, violates this provision. Appropriate legal action may include, but is not limited to, removing the offending content from the Service, suspending or terminating the account of such violators and reporting you to the law enforcement authorities.</p>
                <P class="mb-4 leading-5">By using the Service, you agree to the following conditions of use:</p>
                <ol>
                    <li class="mb-4 ml-4 leading-5" type=a>You will not engage in any conversation or otherwise upload any content that (i) infringes any intellectual property or other proprietary rights of any party; (ii) you do not have right to upload under any law or under contractual or fiduciary relationships; (iii) contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunication equipment; (iv) poses or creates a privacy or security risk to any person; (v) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, “junk mail,” “spam,” “chain letters,” pyramid schemes,” “contests,” “sweepstakes,” or any other form of solicitation; (vi) is unlawful, harmful, threatening, abusive, harassing, tortious, violent, defamatory, vulgar, obscene, pornographic, libelous, invasive of another’s privacy, hateful racially, ethnically, or based on any other protected personal characteristic; or (vii) in the sole judgment of DLY is objectionable or which restricts or inhibits any other person from using or enjoying the Service, or which may expose DLY or its users to any harm or liability of any type;</li>
                    <li class="mb-4 ml-4 leading-5" type=a>You will not interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service;</li>
                    <li class="mb-4 ml-4 leading-5" type=a> You will not violate any applicable local, state, national or international law, or any regulations having the force of law;</li>
                    <li class="mb-4 ml-4 leading-5" type=a> You will not obtain or attempt to obtain or collect contact information of other users from the Service by any means for purposes of soliciting, advertising, promoting, or offering to sell or buy any goods or services unless specifically authorized by DLY; and</li>
                    <li class="mb-4 ml-4 leading-5" type=a> You will not further or promote any criminal activity or enterprise or provide instructional information about illegal activities.</li>
                </ol>
            </li>
            <li class="mb-4 ml-4 leading-5"> <strong>Use of Your Content –</strong> DLY may use Your Content in a number of different ways, which include, but are not limited to, publicly displaying it, reformatting it, incorporating it into advertisements and other works, creating derivative works from it, promoting it, distributing it, and allowing others to do the same in connection with their own websites and media platforms. You hereby irrevocably grant DLY world-wide, perpetual, non-exclusive, royalty-free, assignable, sublicensable, transferable rights to use Your Content for any purpose. You irrevocably waive, and cause to be waived, against DLY and its users and claims and assertions of moral rights or attribution with respect to Your Content. </li>
            <li class="mb-4 ml-4 leading-5"><strong>Advertising  - </strong>DLY and its licensees may publicly display advertisements, paid content, and other information nearby or in association with Your Content. You are not entitled to any compensation for such advertisements. </li>
            <li class="mb-4 ml-4 leading-5"><strong>Removal of Content – </strong>DLY reserves the right to remove, screen, edit, or reinstate Your Content that is in violation of the Terms of Service, Community Guidelines or Privacy Policy at its sole discretion for any reason and without notice to you.</li>
            <li class="mb-4 ml-4 leading-5"><strong>Disclaimer –</strong> User Content does not reflect the opinion of DLY. DLY may not be held liable for Content of any user.</li>
        </ol>
        <P class="mb-4 leading-5"><strong><u>Indemnity</u></strong></p>
        <P class="mb-4 leading-5">You agree to indemnify, defend, and hold us and our subsidiaries, affiliates, officers, agents, employees, contractors, partners and licensors harmless from and against any and all suits, actions, losses, claims, proceedings, demands, expenses, damages, settlements, judgments, injuries, liabilities, obligations, risks, and costs, including, without limitation, reasonable attorneys’ fees, due to, relating to, or arising out of: (i) your use of the Services; (ii) your violation of these Terms; (iii) any Content you provide; (iv) your negligence, fraud, or willful misconduct; (v) your Account; and/or (vi) your violation of any law or regulation or any rights of another. We reserve the right, at your expense, to assume the exclusive defense and control of any matter which you are required to indemnify against, and you agree to cooperate in our defense of such matter. This indemnification will survive any termination of these Terms.</p>
        <P class="mb-4 leading-5"><strong><u>Disclaimer of Warranties</u></strong></p>
        <P class="mb-4 leading-5">YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. DLY INC. EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.</p>
        <P class="mb-4 leading-5">DLY INC. MAKES NO WARRANTY THAT (I) THE SERVICE WILL MEET YOUR REQUIREMENTS, (II) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, OR (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS.</p>
        <P class="mb-4 leading-5">DLY IS UNDER NO OBLIGATION TO ENFORCE THESE TERMS OF SERVICE ON BEHALF OF ANY USER AGAINST ANOTHER USER. USER CONTENT IS MONITORED BY DLY FOR ADHERENCE TO THESE TERMS OF SERVICE AND USERS ARE ENCOURAGED TO REPORT ANY PERCEIVED MISUSE OR VIOLATION OF THESE TERMS BY ANOTHER USER. DLY RESERVES THE RIGHT TO INVESTIGATE SUCH REPORTS AND TAKE APPROPRIATE ACTION AT ITS SOLE DISCRETION.</p>
        <P class="mb-4 leading-5"><strong><u>Limitation of Liability</u></strong></p>
        <P class="mb-4 leading-5">YOU UNDERSTAND AND AGREE THAT WE WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQU</p>
        <P class="mb-4 leading-5">ENTIAL, PUNITIVE, EXEMPLARY, OR SPECIAL DAMAGES, WHETHER BASED IN CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH ACCESS TO OR USE OF THE SERVICES, INCLUDING, WITHOUT LIMITATION, ANY MATERIALS, SERVICES AND/OR PRODUCTS WE HAVE PROVIDED TO YOU ON OR THROUGH THE SERVICES, WHETHER OR NOT YOU HAVE PURCHASED OR PROVIDED ANY CONSIDERATION FOR SUCH, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING BUT NOT LIMITED TO: (A) ANY ACTION TAKEN IN CONNECTION WITH AN INVESTIGATION BY LAW ENFORCEMENT AUTHORITIES REGARDING YOUR OR ANY OTHER PARTY’S USE OF THE SERVICES; (B) ANY ACTION TAKEN IN CONNECTION WITH COPYRIGHT OR OTHER INTELLECTUAL PROPERTY OWNERS; (C) ANY DAMAGE TO ANY USER’S COMPUTER, MOBILE DEVICE, OR OTHER EQUIPMENT OR TECHNOLOGY; (D) RELIANCE BY ANY PARTY ON ANY CONTENT OBTAINED THROUGH USE OF THE SERVICES; OR (E) WHETHER CAUSED IN WHOLE OR IN PART BY NEGLIGENCE, ACTS OF GOD, TELECOMMUNICATIONS FAILURE, THEFT OR DESTRUCTION OF, OR UNAUTHORIZED ACCESS TO THE SERVICES, OR RELATED INFORMATION OR PROGRAMS, THAT ARISE IN CONNECTION WITH: (1) MISTAKES OR OMISSIONS IN, OR DELAYS IN TRANSMISSION OF, INFORMATION TO OR FROM THE USER; (2) INTERRUPTIONS IN TELECOMMUNICATIONS CONNECTIONS TO THE SERVICES; OR (3) VIRUSES.</p>
        <P class="mb-4 leading-5">OUR TOTAL LIABILITY TO YOU FROM ALL CAUSES OF ACTION AND UNDER ALL THEORIES WILL BE LIMITED TO THE AMOUNT YOU HAVE PAID FOR THE USE OF THE SERVICES, IF ANY, OR, IF GREATER, ONE HUNDRED DOLLARS ($100). YOU ALSO ACKNOWLEDGE AND AGREE THAT YOU HAVE VIEWED OR USED THE SERVICES WITH A FULL UNDERSTANDING OF THE LIMITATION OF OUR LIABILITY IN THESE TERMS.</p>
        <P class="mb-4 leading-5">SOME JURISDICTIONS DO NOT ALLOW EXCLUSIONS OF LIABILITY FOR CERTAIN TYPES OF DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU TO THE EXTENT PROHIBITED BY LAW. IN SUCH CASES, OUR LIABILITY WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICE OR WITH THESE TERMS OF SERVICE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE SERVICE.</p>
        <P class="mb-4 leading-5"><strong>Arbitration, Disputes, and Choice of Law</strong></p>
        <P class="mb-4 leading-5">Any controversy or claim arising out of or relating to: (a) these Terms, or the breach thereof; or (b) your access to or use of DLY services; shall be settled by arbitration administered by the American Arbitration Association. Arbitration will be conducted by a neutral arbitrator in accordance with the American Arbitration Association’s (“AAA”) rules and procedures, including the AAA’s Consumer Arbitration Rules and judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof. The arbitrator will issue a reasoned award in writing, including all findings of fact and law upon which the award was made. Arbitrations will be held in Atlanta, Georgia but the parties may choose for themselves whether to appear in person, by phone, or through the submission of documents. The arbitration shall be governed by the laws of the State of Georgia. The prevailing party shall be entitled to an award of reasonable attorneys’ fees.</p>
        <P class="mb-4 leading-5"><strong><u>Termination</u></strong></p>
        <P class="mb-4 leading-5">You may terminate by closing your account AND discontinuing access and use of the Service AND notice to DLY of termination <a href="mailto:info@differentlikeu.com">info@differentlikeu.com.</a></p>
        <P class="mb-4 leading-5">DLY reserves the right to terminate account at any time and for any reason.</p>
        <P class="mb-4 leading-5"><strong><u>Privacy</u></strong></p>
        <P class="mb-4 leading-5">At DLY, Inc., we respect the privacy of our users. For details, please see our Privacy Policy. By using the Service, you consent to our collection and use of personal data as outlined therein.</p>
    </div>
</div>